v@startuml

class Ship {

# shipName : String
# yearBuilt : String

+ setYearBuilt(yearBuilt : String) : void
+ getYearBuilt() : String

+ setShipName(shipName : String) : void
+ getShipName () : String

+ toString() : String
+ printShip() : void

}

class CargoShip {

# cargoCapacityInTonnage : int

+ setCargoCapacityInTonnage(cargoCapacityInTonnage : int) : void
+ getCargoCapacityInTonnage() : int
+ toString() : String

}

class CruiseShip {

# maxNumberPassengers : int

+ setMaxNumberPassengers (maxNumberPassengers : int) : void
+ getMaxNumberPassengers : int
+ toString() : String
}

class Driver {
+ main ( args : String [] ) : void
+ toString() : String
}


Ship <|-- CargoShip
Ship <|-- CruiseShip




@enduml